### ISSUE TITLE
Composite actions: support for existing audits

### ISSUE THREAD

**Issue by woodruffw** [zizmorcore/zizmor#350]
#331 will add composite action support. From there, the current audits need to be extended to work with composite actions, where appropriate.

- [x] artipacked #896 
- [x] dangerous-triggers (N/A)
- [x] excessive-permissions (N/A)
- [x] hardcoded-container-credentials (N/A?)
- [x] impostor-commit: #331
- [x] known-vulnerable-actions @ubiratansoares #367
- [x] ref-confusion @ubiratansoares #365
- [x] self-hosted-runner (N/A?)
- [x] template-injection: #331
- [x] use-trusted-publishing #899 
- [x] unpinned-uses @ubiratansoares #364
- [x] insecure-commands #359
- [x] github-env #358 
- [x] cache-poisoning (N/A?)

**Comment by woodruffw** [comment]
I'm going to keep burning this down, but I would appreciate help as well! If anybody is interested in working on one of these, leave a comment here and I'll assign it to you 🙂

**Comment by ubiratansoares** [comment]
@woodruffw Happy to help here!

Let me give a try on `known-vulnerable-actions`, `unpinned-uses, and `ref-confusion`, they don't look too hard and I can learn a bit more about their inner details along the way. I'll raise individual PRs for each one, for the sake of easier reviews 🙂

**Comment by ubiratansoares** [comment]
@woodruffw Happy new year 🎉🎉🎉

If ok for you, I'm happy take the 2 remaining audits, so we get the all audits supported in Composite Actions 🙂

**Comment by woodruffw** [comment]
That would be awesome, thank you @ubiratansoares! And happy new year!

**Comment by woodruffw** [comment]
#896 and #899 wrap this up 🙂
